### ISSUE TITLE
Add WPSE API & Widget

### ISSUE THREAD

**Issue by swissspidy** [markoheijnen/WordPress-contributions#12]
In your blog post (http://markoheijnen.com/sharing-that-you-contributed-to-wordpress/) about this plugin you mentioned StackExchange as an additional source.

StackExchange has a nice API (https://api.stackexchange.com/docs) and one could retrieve questions, answers and badges from a user, showing his reputation on WPSE.

**Comment by markoheijnen** [comment]
This was also mentioned in #10 but yes this should have been a ticket.
